### ISSUE TITLE
Convert to Jekyll

### ISSUE THREAD

**Issue by davidgatti** [G-atti/sabina.gatti.pl#1]
[milo-1-2-1-1.zip](https://github.com/G-atti/sabina.gatti.pl/files/4497990/milo-1-2-1-1.zip)

The template attached can be found above, and bellow is a list of pages that I want to use. 

- page-category
- page-about
- page-404
- home-fullwidth

From the template we have to remove the popular posts, since with a static site we can't calculate that.

**Comment by tolgaouz** [comment]
pushed the repo, didn't make a PR yet.
