### ISSUE TITLE
New set of changes

### ISSUE THREAD

**Issue by davidgatti** [G-atti/sabina.gatti.pl#4]
Things to change

- [x] make the footer sticky - I should slowly stop telling you this, this should be something done on all website by default.
- [x] when you paginate, the active number must be bold, or highlighted, check the template if they have something if not, just make it bold, so it is clear on what page are you in.
- [x] remove the instagram section at the bottom of the page.
- [x] instead of 3 weeks ago in category1, just put a time stamp of the day the post was created
- [x] when you clcik on an article the pagination is not displayed, but the lines for separation are, make sure that the last line is also removed, since now it looks as if something was missing
- [x] On the home page when you have all the articles, instead of the weeks the post was created, replace that with the time stamp
- [x] add a books page, and make the view same as the article one, since there will be a book image with a short description.
- [x] make a terms page with dummy text
- [x] make a privacy policy page with dummy text
- [x] for the contact page, add the code that we have for consulting.
- [x] Make the tiles correct

**Comment by tolgaouz** [comment]
I'm combining all these in a new branch and separating each listing with different commits. Is that okay?

**Comment by davidgatti** [comment]
This is perfect :)
