### ISSUE TITLE
Final mile

### ISSUE THREAD

**Issue by davidgatti** [G-atti/sabina.gatti.pl#6]
# Sticky footer

![Screen Shot 2020-05-23 at 7 11 08 PM](https://user-images.githubusercontent.com/411114/82736326-32386c80-9d29-11ea-875b-811da5e365e0.png)

# Consistent Header

![Screen Shot 2020-05-23 at 7 11 57 PM](https://user-images.githubusercontent.com/411114/82736345-4f6d3b00-9d29-11ea-8df7-17f39ea64b76.png)

The font needs to be the same as the rest.

# All pages needs to have the same margins 

![Screen Shot 2020-05-23 at 7 21 54 PM](https://user-images.githubusercontent.com/411114/82736526-b3443380-9d2a-11ea-95ec-a671adcf5fa3.png)

# Page titles and otehr data

- Make sure all pages titles are set
- Also all the OGs

# Unnecessary line

![Screen Shot 2020-05-23 at 7 24 19 PM](https://user-images.githubusercontent.com/411114/82736905-4aaa8600-9d2d-11ea-84fc-42786422695d.png)

# Unnecessary line

![Screen Shot 2020-05-23 at 7 43 28 PM](https://user-images.githubusercontent.com/411114/82736964-b987df00-9d2d-11ea-9abb-e7ef6b64bf98.png)

**Comment by tolgaouz** [comment]
Changes are pushed to jekyll branch
